/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Home: typeof import('./src/components/Home.vue')['default']
    NewEmployeeForm: typeof import('./src/components/NewEmployeeForm.vue')['default']
    RegisterConsumption: typeof import('./src/components/RegisterConsumption.vue')['default']
    Reports: typeof import('./src/components/Reports.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Snackbar: typeof import('./src/components/Snackbar.vue')['default']
  }
}
